In [1]:
!nvidia-smi

Mon May 15 20:59:35 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 528.02       Driver Version: 528.02       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   53C    P3    13W /  30W |      0MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

# PyTorch Fundamentals 

In [1]:
import torch

In [4]:
print(torch.__version__)

2.0.1+cu118


In [3]:
torch.cuda.is_available()

True

## Libraries

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Introduction to Tensors

In [6]:
#Scalar 
scalar = torch.tensor(7)   
scalar

tensor(7)

In [7]:
scalar.ndim

0

In [8]:
# Get tensor back as python int
scalar.item()

7

In [9]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [13]:
#Matrix
matrix = torch.tensor([[7,8],
                      [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
matrix.ndim

2

In [16]:
matrix[1]

tensor([ 9, 10])

In [17]:
matrix.shape

torch.Size([2, 2])

In [22]:
#Tensor
tensor = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]],
                      [[11,12,13],
                      [14,15,16],
                      [17,18,19]]])
tensor

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]]])

In [23]:
tensor.ndim

3

In [24]:
tensor.shape

torch.Size([2, 3, 3])

In [27]:
tensor[0][0][0]

tensor(1)

# Random Tensors 

Random tensors are important because the way many neural networks learn is that they start with tensor full of random numbers and then adjust those random numbers to better represent the data.


#### Start with random numbers -> Look at data -> Update random numbers -> Look at data -> Update random numbers

In [28]:
# Create a random tensor of shape(3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9246, 0.7421, 0.3062, 0.6292],
        [0.2319, 0.7405, 0.8345, 0.1830],
        [0.8604, 0.9996, 0.7293, 0.1366]])

In [29]:
random_tensor.ndim

2

In [30]:
# Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [31]:
random_image_size_tensor

tensor([[[0.9433, 0.3486, 0.1772],
         [0.3701, 0.6822, 0.4672],
         [0.0930, 0.8386, 0.9701],
         ...,
         [0.4907, 0.4808, 0.1108],
         [0.3881, 0.5344, 0.2763],
         [0.2444, 0.1077, 0.6099]],

        [[0.1798, 0.7810, 0.7923],
         [0.9473, 0.7779, 0.7447],
         [0.8669, 0.9302, 0.2473],
         ...,
         [0.8604, 0.2973, 0.3019],
         [0.7493, 0.8439, 0.5904],
         [0.7559, 0.6519, 0.7260]],

        [[0.6487, 0.6584, 0.3991],
         [0.9771, 0.6113, 0.2479],
         [0.5574, 0.3044, 0.6921],
         ...,
         [0.1153, 0.5434, 0.9658],
         [0.6614, 0.9053, 0.7155],
         [0.0573, 0.8617, 0.3707]],

        ...,

        [[0.0827, 0.6084, 0.6361],
         [0.4048, 0.2028, 0.5064],
         [0.7717, 0.9795, 0.2366],
         ...,
         [0.6520, 0.6412, 0.5797],
         [0.3115, 0.5267, 0.8841],
         [0.5096, 0.5162, 0.4233]],

        [[0.6599, 0.8470, 0.1163],
         [0.7245, 0.8260, 0.3260],
         [0.

## Zeros and Ones 

In [32]:
# Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [33]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [34]:
# Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [35]:
ones.dtype

torch.float32

In [36]:
ones * random_tensor

tensor([[0.9246, 0.7421, 0.3062, 0.6292],
        [0.2319, 0.7405, 0.8345, 0.1830],
        [0.8604, 0.9996, 0.7293, 0.1366]])

## Creating a range of tensors and tensors-like 

In [39]:
# use torch.arange()
one_to_ten = torch.arange(start=1,end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes 

#### Tensor datatypes is one of the 3 big errors in PyTorch

##### 1. Tensors not right datatype
##### 2. Tensors not right shape
##### 3. Tensors not on the right device

In [40]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,             # What datatype of tensor
                               device=None,            # What device is your tensor on
                               requires_grad=False)    # Whether or not to track gradients
float_32_tensor

tensor([3., 6., 9.])

In [41]:
float_32_tensor.dtype

torch.float32

In [43]:
# Converting in to float 16 tensor
float_16_tensor = float_32_tensor.type(torch.int16)
float_16_tensor

tensor([3, 6, 9], dtype=torch.int16)

## Getting information from tensors (Tensor attributes)


#### 1. Tensors not right datatype - To do fet datatyoe from a tensor, can use 'tensor.dtype'
#### 2. Tensors not right shape - To get shape from a tensor, can use 'tensor.shape'
#### 3. Tensors not on the right device - to get device from a tensor, can use 'tensor.device'

In [44]:
# Create a tensor

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5063, 0.0014, 0.8348, 0.0816],
        [0.8060, 0.6375, 0.2853, 0.8314],
        [0.6360, 0.6980, 0.7637, 0.1037]])

In [45]:
# Find out the details of the tensor 

print(some_tensor)

print(f'Datatype of the tensor: {some_tensor.dtype}')

print(f'Shape of the tenor: {some_tensor.shape}')

print(f'Device of the tensor is on: {some_tensor.device}')

tensor([[0.5063, 0.0014, 0.8348, 0.0816],
        [0.8060, 0.6375, 0.2853, 0.8314],
        [0.6360, 0.6980, 0.7637, 0.1037]])
Datatype of the tensor: torch.float32
Shape of the tenor: torch.Size([3, 4])
Device of the tensor is on: cpu


## Manipulating Tensors (tensor operations)

#### 1. Tensor operations include:

* Addition
* Subtraction 
* Multiplication
* Division
* Matrix multiplication

In [10]:
# Create a tensor 

tensor = torch.tensor([1,2,3])
tensor + 100

tensor([101, 102, 103])

In [11]:
# multiply tensor by 10

tensor * 10

tensor([10, 20, 30])

In [12]:
# Subtraction 

tensor - 10

tensor([-9, -8, -7])

In [13]:
# Try out PyTorch in-build functions

torch.mul(tensor, 10)

tensor([10, 20, 30])

## Matrix multiplication

#### Two main ways of perfoming multiplication in neural networks and deep learning:

* Element wise multiplication
* Dot product

#### There are two main rules that perfoming matrix multiplication needs to satisfy:

1. The **inner dimensions** must match:

* (3,2) @ (3,2) won't work
* (2,3) @ (3,2) will work
* (3,2) @ (2,3) will work

In [47]:
# Element wise multiplication

print(tensor, '*', tensor)
print(f'Equals: {tensor * tensor}')

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]]]) * tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]]])
Equals: tensor([[[  1,   4,   9],
         [ 16,  25,  36],
         [ 49,  64,  81]],

        [[121, 144, 169],
         [196, 225, 256],
         [289, 324, 361]]])


In [48]:
torch.matmul(tensor, tensor)

tensor([[[ 30,  36,  42],
         [ 66,  81,  96],
         [102, 126, 150]],

        [[510, 546, 582],
         [636, 681, 726],
         [762, 816, 870]]])

## One of the most common errors in deep learning: Shape errors 

In [49]:
tensor_A = torch.tensor([[1,2],
                      [3,4],
                      [5,6]])
tensor_B = torch.tensor([[7,10],
                       [8,11],
                       [9,12]])

torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [50]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

## To fix out tensor shape issue, we can manipulate the shape of one our tensors

A **transpose** switches the axes or dimensions of given tensor

In [29]:
tensor_B.T, tensor_B

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

In [58]:
tensor1 = torch.rand(2,4)
tensor2 = torch.rand(2,3)

mul = torch.mm(tensor1T, tensor2)

In [59]:
mul

tensor([[1.1393, 0.8931, 0.8382],
        [0.5990, 0.3105, 0.5575],
        [0.6393, 0.2847, 0.6291],
        [0.9023, 0.8973, 0.5245]])

In [60]:
mul.shape

torch.Size([4, 3])

In [36]:
print(f'The matrix multiplication is:  {torch.mm(tensor_A, tensor_B.T)}')

The matrix multiplication is:  tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


## Finding the min, max, mean, sum, etc (tensor aggregation) 

In [43]:
# Create a tensor

x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [49]:
# Finding min and max

torch.min(x), torch.max(x)

(tensor(0), tensor(90))

In [44]:
# torch.mean() function requres a tensor of float32 datatype to work
torch.mean(x.type(torch.float32))

tensor(45.)

In [50]:
# Finding the sum

torch.sum(x)

tensor(450)

## Finding the positional min and max 

In [51]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [54]:
# Minimum value of arg min

x.argmin()

tensor(0)

In [55]:
# Maximum value of arg max

x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* **Reshaping** - reshapes an input tensor to a defined shape 
* **View** - Return a view of an input tensor of certain shape but keep the same memory as the original tensor.
* **Stacking** - Combine multiple tensors on top of each other(vstack) or side by side (hstack)
* **Squeeze** - removes all 1 dimensions from a tensor
* **Unsqueze** - add a 1 dimensions to a target tensor
* **Permute** - Teturn a view of the input with dimension permuted (swapped) in a certain way

In [72]:
# Let's create a tensor

x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [73]:
# Add an extra dimension

x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [74]:
# Change the view

z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [75]:
# Changing Z changes x (because a view of a tensor shares the same memory as the original memory location)

z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [78]:
# Stack tensors on the top of each other

x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [79]:
# Squeezing - removes all single dimension from a target tensor

x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [81]:
x_reshaped.shape

torch.Size([1, 9])

In [80]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [82]:
x_reshaped.squeeze().shape

torch.Size([9])

In [91]:
x_reshaped.unsqueeze(dim=1)

tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]]])

In [96]:
# Permute - Rearrange the dimensions of a target tensor in a specified order

x_original = torch.rand(size=(224,224,3))

# Permute the original tensor to rearrange the axis (or dim) order

x_perumted = x_original.permute(2, 0, 1) # shits the axis 

print(f'Previous shape: {x_original.shape}')
print(f'New shape: {x_perumted.shape}')

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [100]:
x_original[0,0,0] = 978952
x_original[0,0,0], x_perumted[0,0,0]

(tensor(978952.), tensor(978952.))

## Indexing (selecting data from tensors)

### Indexing with PyTorch is similar to indexing with Numpy

In [7]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [8]:
# Let's index on our new tensor

x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [9]:
# Let's index on the middle bracket (dim=1)

x[0][0]

tensor([1, 2, 3])

In [10]:
# Let's index on the most inner bracket (last dimension)

x[0][0][0]

tensor(1)

In [13]:
# you can also use ':' to select 'all' of a target dimension

x[0, 0]

tensor([1, 2, 3])

In [14]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension

x[:,1]

tensor([[4, 5, 6]])

In [15]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension

x[:,:,1]

tensor([[2, 5, 8]])

In [128]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimensions

x[0,0,:]

tensor([1, 2, 3])

In [132]:
# Index on x to return 9

x[:,:,2]

tensor([[3, 6, 9]])